[package]
name = "myfs"
version = "0.1.0"
authors = ["Felix KÃ¶pge <fkoep@mailbox.org>"]
license = "MIT"

[features]
default = ["xdg"]

[dependencies]
bitflags = "0.7"
lazy_static = "*"
tempdir = { version = "*" }
xdg = { version = "*", optional = true }
